# kubernetes resources to be managed by kustomize
resources:
#- clusterissuer.yaml
- db-service.yaml
- db-statefulset.yaml
- fastapi-service.yaml
- fastapi-deployment.yaml
- pgadmin-service.yaml
- pgadmin-deployment.yaml
- secret-db.yaml
- postgres-data-persistentvolumeclaim.yaml
- ingress-api.yaml
- ingress-pgadmin.yaml
- configMap-pgadmin.yaml
- configMap-postgres.yaml

#Customizations that need to be made

namespace: kustomize

commonLabels:
  company: Devops-ykadi

commonAnnotations: 
      exam: devops-kubernetes-youss