apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-data
  name: postgres-data
  namespace: standard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
status: {}
