namespace: helm

appName: pgadmin-default


# fastapi Values

fastapiName: fastapi
replicaCountAPI: 1


image:
  name: ykadi/fastapi
  tag: v2.0


ApiPort: 5000
serviceApiPort: 5000


## Postgresql values
DatabaseName: db
DatabaseLabel: db

replicaCountDB: 1

volumeDB:
    name: postgres-data
    accessModes: ReadWriteOnce
    storage: 500Mi
    mountPath: /var/lib/postgresql/data

pvcPostgres: postgres-pvc


dbPort: 5432
servicedbPort: 5432 


secretDbName: postgresql-fastapi-userpass


# HPA values
hpa:
   maxReplicas: 2
   minReplicas: 1


# Ingress values



ingressClassName: traefik

hostIngress: api.devops-youss.cloudns.ph 
hostIngress2: pgad.devops-youss.cloudns.ph