
namespace: prod

# Fastapi Values
fastapiName: fastapi-prod
replicaCountAPI: 1

## Postgresql values

replicaCountDB: 2
volumeDB:
    storage: 10Gi

# PGadmin Values
appName: pgadmin-prod


# HPA values
hpa:
   maxReplicas: 6
   minReplicas: 3