
namespace: dev


# Fastapi Values
fastapiName: fastapi-dev
replicaCountAPI: 1

## Postgresql values

replicaCountDB: 1

volumeDB:
    storage: 1Gi
   



# PGadmin Values
appName: pgadmin-dev


# HPA values
hpa:
   maxReplicas: 1
   minReplicas: 1