apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapPostgres }}
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_DB: storedb
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRES_USER: admin

