apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.DatabaseLabel }}
  name: {{ .Values.DatabaseName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCountDB }}
  serviceName: db
  selector:
    matchLabels:
      app: {{ .Values.DatabaseLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.DatabaseLabel }}
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: storedb
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretDbName }}
                  key: password
            - name: POSTGRES_USER
              value: admin
          image: postgres:12.0-alpine
          name: db
          ports:
            - containerPort: {{ .Values.dbPort }}
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: {{ .Values.volumeDB.mountPath }}
              name: {{ .Values.volumeDB.name }}
      volumes:
          - name: {{ .Values.volumeDB.name }}
            persistentVolumeClaim:
              claimName: {{ .Values.pvcPostgres }}              
  # volumeClaimTemplates:
  #   - metadata:
  #       name: {{ .Values.volumeDB.name }}
  #     spec:
  #       accessModes: [ "ReadWriteMany" ]
  #       resources:
  #         requests:
  #           storage: {{ .Values.volumeDB.storage }}
