apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.DatabaseLabel }}
  name: db
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: postgresql
      port: {{ .Values.servicedbPort }}
      targetPort: {{ .Values.dbPort }}
  selector:
    app: {{ .Values.DatabaseLabel }}
status:
  loadBalancer: {}
