apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.fastapiName }}
  name: {{ .Values.fastapiName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCountAPI }}
  selector:
    matchLabels:
      app: {{ .Values.fastapiName }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.fastapiName }}
    spec:
      containers:
        - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}" 
          name: {{ .Values.fastapiName }}
          ports:
            - containerPort: {{ .Values.ApiPort }}
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
