apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.fastapiName }}
  name: {{ .Values.fastapiName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.serviceApiPort }}
      targetPort: {{ .Values.ApiPort }}
  selector:
    app: {{ .Values.fastapiName }}
status:
  loadBalancer: {}
