apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-fastapi
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Ajoutez vos annotations ici
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - {{ .Values.hostIngress }}
    secretName: letsencrypt-prod-api
  rules:
  - host: {{ .Values.hostIngress }} 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fastapi
            port:
              number: 5000
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: fastapi
            port:
              number: 5000
      - path: /users/count
        pathType: Prefix
        backend:
          service:
            name: fastapi
            port:
              number: 5000