apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.volumeDB.name }}
  name: {{ .Values.pvcPostgres }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.volumeDB.accessModes }}
  resources:
    requests:
      storage: {{ .Values.volumeDB.storage }}
status: {}
