apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-data
  name: {{ .Values.pvcPostgres }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
